import { Candle } from "../types/Candle";

export const candles: Candle[] = [
  {
    name: "Blooming Bliss",
    id: "1",
    price: 15,
    image: "/images/products/herbal_serenity.jpg",
    alt: "Blooming Bliss Candle",
    desc: "A strong floral fragrance that effortlessly captures the essence of a gardenia bloom. This scent is a sensory journey where each whiff unveils a pure and enchanting aroma with hints of jasmine, rose, and lily.",
    favorite: true,
  },
  {
    name: "Festive Melody",
    id: "2",
    price: 15,
    image: "/images/products/herbal_serenity.jpg",
    alt: "Festive Melody Candle",
    desc: "A delightful tapestry of festive aromas, weaving together the bold warmth of red cinnamon with the inviting embrace of spiced apple and citrusy orange notes capturing the essence of holiday cheer.",
    favorite: true,
  },
  {
    name: "Herbal Serenity",
    id: "3",
    price: 15,
    image: "/images/products/herbal_serenity.jpg",
    alt: "Herbal Serenity Candle",
    desc: "The very essence of a lavender field in full bloom has been captured for your enjoyment. As the fragrance unfolds, the herbal symphony of sage introduces a touch of earthiness, grounding the lavender's ethereal quality.",
    favorite: true,
  },
  {
    name: "Pine Reverie",
    id: "4",
    price: 15,
    image: "/images/products/herbal_serenity.jpg",
    alt: "Pine Reverie Candle",
    desc: "A fresh pine aroma with earthy balsamics, woody notes, and a touch of sweetness. Serves as an excellent cooling pine and wood bouquet during the holidays or as a balsamic pine incense all year round.",
    favorite: true,
  },
  {
    name: "Tropical Bloom",
    id: "5",
    price: 15,
    image: "/images/products/herbal_serenity.jpg",
    alt: "Tropical Bloom Candle",
    desc: "A clean and fresh jasmine blend with a bright floral note. This aroma evokes thoughts of a warm sunny day given its native tropical and subtropical roots from the temperate regions of Europe, Asia, and Africa.",
    favorite: true,
  },
  {
    name: "Citrus Frost",
    id: "6",
    price: 15,
    image: "/images/products/herbal_serenity.jpg",
    alt: "Citrus Frost Candle",
    desc: "A musky scent harmoniously blending clean citrus and sweet floral undertones. Infused with refreshing mint this cologne-type scent, enriched with lemon, eucalyptus, and citronella, is ideal for elevating any occasion.",
    favorite: false,
  },
  {
    name: "Crisp Fusion",
    id: "7",
    price: 15,
    image: "/images/products/herbal_serenity.jpg",
    alt: "Crisp Fusion Candle",
    desc: "The invigorating embrace of a clean, fresh citrus blend that harmonizes zesty orange, succulent strawberries, delicate jasmine, and luscious raspberries. This scent evokes the vibrancy of a bountiful fruit garden.",
    favorite: false,
  },
  {
    name: "Sunny Petals",
    id: "8",
    price: 15,
    image: "/images/products/herbal_serenity.jpg",
    alt: "Sunny Petals Candle",
    desc: "An uplifting scent where sparkling citrus dances with the sweet florals and vibrant green leaves. This aromatic symphony creates an invigorating fragrance capturing the essence of a sun-kissed garden in full bloom.",
    favorite: false,
  },
  {
    name: "Timber Essence",
    id: "9",
    price: 15,
    image: "/images/products/herbal_serenity.jpg",
    alt: "Timber Essence Candle",
    desc: "A soothing ambiance of natural woody aromas gently caressed by the allure of sweet spices. The perfect fusion of earthy richness and subtle sweetness, this scent invites you to unwind in a cocoon of tranquility and warmth.",
    favorite: false,
  },
  {
    name: "Vanilla Timber",
    id: "10",
    price: 15,
    image: "/images/products/herbal_serenity.jpg",
    alt: "Vanilla Timber Candle",
    desc: "Sweet vanilla delicately baked over warm cedarwood creates a captivating blend that whispers of cozy kitchens and sun-dappled forests, leaving a trail of irresistible warmth wherever it touches.",
    favorite: false,
  },
];
